root_dir = ".."
# output directory
datasets_dir = f"{root_dir}/_datasets"
# input directory
country_geojson_dir = f"{root_dir}/country_geojson"
json_dir = f"{datasets_dir}/json"
python_path = f"{root_dir}/python"
vectors_path = f"{python_path}/vectors.json"
# for use when run with --ci flag
remote_target_branch = "rdl-1.0"

# Search configuration constants (matching front-end hybrid search logic)
KEYWORD_SCORE_MIN = 0.75
KEYWORD_SCORE_MAX = 1.0
SCORED_FIELDS = [
    "catalog",
    "category",
    "creator.name",
    "dataset_id",
    "description",
    "details",
    "countries",
    "license",
    "notes",
    "project",
    "resources",
    "title",
]
SEMANTIC_MAX_RESULTS = 50
SEMANTIC_MIN_SCORE = 0.25

schema_url = "https://docs.riskdatalibrary.org/en/1__0__0/rdls_schema.json"

dataset_catalogs = {
    "oasishub.co": "OASIS HUB",
    "drmkc.jrc.ec.europa.eu/risk-data-hub#": "JRC DRMKC risk hub",
    "data.humdata.org": "Humanitarian Data Exchange",
    "emdat.be": "EM-DAT (Emergency Events Database)",
    "gdacs.org": "GDACS (Global Disaster Alert and Coordination System)",
    "risk.preventionweb.net": "GAR PreventionWeb",
    "ncei.noaa.gov": "NOAA",
    "cds.climate.copernicus.eu": "Copernicus Climate Data Store",
    "earthdata.nasa.gov": "NASA Earth Data",
    "datacatalog.worldbank.org": "World Bank Data Catalog",
    "geohub.data.undp.org": "UNDP GeoHub",
    "unosat.org": "UNOSAT",
    "fao.org": "FAO Data",
    "data.adb.org": "Asian Development Bank Data Library",
    "dataportal.opendataforafrica.org": "African Development Bank Data Portal",
    "openstreetmap.org": "OpenStreetMap",
    "scihub.copernicus.eu": "Copernicus Open Access Hub",
    "sedac.ciesin.columbia.edu": "NASA SEDAC",
    "zenodo.org": "Zenodo",
    "figshare.com": "figshare",
    "datadryad.org": "Dryad",
    "data.europa.eu": "European Data Portal",
}

datasets_countries = {
"ABW": {"title":"Aruba","emoji": "🇦🇼"},
"AFG": {"title":"Afghanistan","emoji": "🇦🇫"},
"AGO": {"title":"Angola","emoji": "🇦🇴"},
"AIA": {"title":"Anguilla","emoji": "🇦🇮"},
"ALA": {"title":"Åland Islands","emoji": "🇦🇽"},
"ALB": {"title":"Albania","emoji": "🇦🇱"},
"AND": {"title":"Andorra","emoji": "🇦🇩"},
"ANT": {"title":"Netherlands Antilles","emoji": ""},
"ARE": {"title":"United Arab Emirates","emoji": "🇦🇪"},
"ARG": {"title":"Argentina","emoji": "🇦🇷"},
"ARM": {"title":"Armenia","emoji": "🇦🇲"},
"ASM": {"title":"American Samoa","emoji": "🇦🇸"},
"ATA": {"title":"Antarctica","emoji": "🇦🇶"},
"ATF": {"title":"French Southern Territories","emoji": "🇹🇫"},
"ATG": {"title":"Antigua and Barbuda","emoji": "🇦🇬"},
"AUS": {"title":"Australia","emoji": "🇦🇺"},
"AUT": {"title":"Austria","emoji": "🇦🇹"},
"AZE": {"title":"Azerbaijan","emoji": "🇦🇿"},
"BDI": {"title":"Burundi","emoji": "🇧🇮"},
"BEL": {"title":"Belgium","emoji": "🇧🇪"},
"BES": {"title":"Caribbean Netherlands","emoji": "🇧🇶"},
"BEN": {"title":"Benin","emoji": "🇧🇯"},
"BFA": {"title":"Burkina Faso","emoji": "🇧🇫"},
"BGD": {"title":"Bangladesh","emoji": "🇧🇩"},
"BGR": {"title":"Bulgaria","emoji": "🇧🇬"},
"BHR": {"title":"Bahrain","emoji": "🇧🇭"},
"BHS": {"title":"Bahamas","emoji": "🇧🇸"},
"BIH": {"title":"Bosnia and Herzegovina","emoji": "🇧🇦"},
"BLM": {"title":"Saint Barthélemy","emoji": "🇧🇱"},
"BLR": {"title":"Belarus","emoji": "🇧🇾"},
"BLZ": {"title":"Belize","emoji": "🇧🇿"},
"BMU": {"title":"Bermuda","emoji": "🇧🇲"},
"BOL": {"title":"Bolivia, Plurinational State of","emoji": "🇧🇴"},
"BRA": {"title":"Brazil","emoji": "🇧🇷"},
"BRB": {"title":"Barbados","emoji": "🇧🇧"},
"BRN": {"title":"Brunei Darussalam","emoji": "🇧🇳"},
"BTN": {"title":"Bhutan","emoji": "🇧🇹"},
"BVT": {"title":"Bouvet Island","emoji": "🇧🇻"},
"BWA": {"title":"Botswana","emoji": "🇧🇼"},
"CAF": {"title":"Central African Republic","emoji": "🇨🇫"},
"CAN": {"title":"Canada","emoji": "🇨🇦"},
"CCK": {"title":"Cocos (Keeling) Islands","emoji": "🇨🇨"},
"CHE": {"title":"Switzerland","emoji": "🇨🇭"},
"CHL": {"title":"Chile","emoji": "🇨🇱"},
"CHN": {"title":"China","emoji": "🇨🇳"},
"CIV": {"title":"Côte d'Ivoire","emoji": "🇨🇮"},
"CMR": {"title":"Cameroon","emoji": "🇨🇲"},
"COD": {"title":"Congo, the Democratic Republic of the","emoji": "🇨🇩"},
"COG": {"title":"Congo","emoji": "🇨🇬"},
"COK": {"title":"Cook Islands","emoji": "🇨🇰"},
"COL": {"title":"Colombia","emoji": "🇨🇴"},
"COM": {"title":"Comoros","emoji": "🇰🇲"},
"CPV": {"title":"Cape Verde","emoji": "🇨🇻"},
"CRI": {"title":"Costa Rica","emoji": "🇨🇷"},
"CUB": {"title":"Cuba","emoji": "🇨🇺"},
"CUW": {"title":"Curaçao","emoji": "🇨🇼"},
"CXR": {"title":"Christmas Island","emoji": "🇨🇽"},
"CYM": {"title":"Cayman Islands","emoji": "🇰🇾"},
"CYP": {"title":"Cyprus","emoji": "🇨🇾"},
"CZE": {"title":"Czech Republic","emoji": "🇨🇿"},
"DEU": {"title":"Germany","emoji": "🇩🇪"},
"DJI": {"title":"Djibouti","emoji": "🇩🇯"},
"DMA": {"title":"Dominica","emoji": "🇩🇲"},
"DNK": {"title":"Denmark","emoji": "🇩🇰"},
"DOM": {"title":"Dominican Republic","emoji": "🇩🇴"},
"DZA": {"title":"Algeria","emoji": "🇩🇿"},
"ECU": {"title":"Ecuador","emoji": "🇪🇨"},
"EGY": {"title":"Egypt","emoji": "🇪🇬"},
"ERI": {"title":"Eritrea","emoji": "🇪🇷"},
"ESH": {"title":"Western Sahara","emoji": "🇪🇭"},
"ESP": {"title":"Spain","emoji": "🇪🇸"},
"EST": {"title":"Estonia","emoji": "🇪🇪"},
"ETH": {"title":"Ethiopia","emoji": "🇪🇹"},
"FIN": {"title":"Finland","emoji": "🇫🇮"},
"FJI": {"title":"Fiji","emoji": "🇫🇯"},
"FLK": {"title":"Falkland Islands (Malvinas)","emoji": "🇫🇰"},
"FRA": {"title":"France","emoji": "🇫🇷"},
"FRO": {"title":"Faroe Islands","emoji": "🇫🇴"},
"FSM": {"title":"Micronesia, Federated States of","emoji": "🇫🇲"},
"GAB": {"title":"Gabon","emoji": "🇬🇦"},
"GBR": {"title":"United Kingdom","emoji": "🇬🇧"},
"GEO": {"title":"Georgia","emoji": "🇬🇪"},
"GGY": {"title":"Guernsey","emoji": "🇬🇬"},
"GHA": {"title":"Ghana","emoji": "🇬🇭"},
"GIB": {"title":"Gibraltar","emoji": "🇬🇮"},
"GIN": {"title":"Guinea","emoji": "🇬🇳"},
"GLO": {"title":"Global","emoji": "🌍"},
"GLP": {"title":"Guadeloupe","emoji": "🇬🇵"},
"GMB": {"title":"Gambia","emoji": "🇬🇲"},
"GNB": {"title":"Guinea-Bissau","emoji": "🇬🇼"},
"GNQ": {"title":"Equatorial Guinea","emoji": "🇬🇶"},
"GRC": {"title":"Greece","emoji": "🇬🇷"},
"GRD": {"title":"Grenada","emoji": "🇬🇩"},
"GRL": {"title":"Greenland","emoji": "🇬🇱"},
"GTM": {"title":"Guatemala","emoji": "🇬🇹"},
"GUF": {"title":"French Guiana","emoji": "🇬🇫"},
"GUM": {"title":"Guam","emoji": "🇬🇺"},
"GUY": {"title":"Guyana","emoji": "🇬🇾"},
"HKG": {"title":"Hong Kong","emoji": "🇭🇰"},
"HMD": {"title":"Heard Island and McDonald Islands","emoji": "🇭🇲"},
"HND": {"title":"Honduras","emoji": "🇭🇳"},
"HRV": {"title":"Croatia","emoji": "🇭🇷"},
"HTI": {"title":"Haiti","emoji": "🇭🇹"},
"HUN": {"title":"Hungary","emoji": "🇭🇺"},
"IDN": {"title":"Indonesia","emoji": "🇮🇩"},
"IMN": {"title":"Isle of Man","emoji": "🇮🇲"},
"IND": {"title":"India","emoji": "🇮🇳"},
"IOT": {"title":"British Indian Ocean Territory","emoji": "🇮🇴"},
"IRL": {"title":"Ireland","emoji": "🇮🇪"},
"IRN": {"title":"Iran, Islamic Republic of","emoji": "🇮🇷"},
"IRQ": {"title":"Iraq","emoji": "🇮🇶"},
"ISL": {"title":"Iceland","emoji": "🇮🇸"},
"ISR": {"title":"Israel","emoji": "🇮🇱"},
"ITA": {"title":"Italy","emoji": "🇮🇹"},
"JAM": {"title":"Jamaica","emoji": "🇯🇲"},
"JEY": {"title":"Jersey","emoji": "🇯🇪"},
"JOR": {"title":"Jordan","emoji": "🇯🇴"},
"JPN": {"title":"Japan","emoji": "🇯🇵"},
"KAZ": {"title":"Kazakhstan","emoji": "🇰🇿"},
"KEN": {"title":"Kenya","emoji": "🇰🇪"},
"KGZ": {"title":"Kyrgyzstan","emoji": "🇰🇬"},
"KHM": {"title":"Cambodia","emoji": "🇰🇭"},
"KIR": {"title":"Kiribati","emoji": "🇰🇮"},
"KNA": {"title":"Saint Kitts and Nevis","emoji": "🇰🇳"},
"KOR": {"title":"Korea, Republic of","emoji": "🇰🇷"},
"KWT": {"title":"Kuwait","emoji": "🇰🇼"},
"LAO": {"title":"Lao People's Democratic Republic","emoji": "🇱🇦"},
"LBN": {"title":"Lebanon","emoji": "🇱🇧"},
"LBR": {"title":"Liberia","emoji": "🇱🇷"},
"LBY": {"title":"Libyan Arab Jamahiriya","emoji": "🇱🇾"},
"LCA": {"title":"Saint Lucia","emoji": "🇱🇨"},
"LIE": {"title":"Liechtenstein","emoji": "🇱🇮"},
"LKA": {"title":"Sri Lanka","emoji": "🇱🇰"},
"LSO": {"title":"Lesotho","emoji": "🇱🇸"},
"LTU": {"title":"Lithuania","emoji": "🇱🇹"},
"LUX": {"title":"Luxembourg","emoji": "🇱🇺"},
"LVA": {"title":"Latvia","emoji": "🇱🇻"},
"MAC": {"title":"Macao","emoji": "🇲🇴"},
"MAF": {"title":"Saint Martin (French part)","emoji": "🇲🇫"},
"MAR": {"title":"Morocco","emoji": "🇲🇦"},
"MCO": {"title":"Monaco","emoji": "🇲🇨"},
"MDA": {"title":"Moldova, Republic of","emoji": "🇲🇩"},
"MDG": {"title":"Madagascar","emoji": "🇲🇬"},
"MDV": {"title":"Maldives","emoji": "🇲🇻"},
"MEX": {"title":"Mexico","emoji": "🇲🇽"},
"MHL": {"title":"Marshall Islands","emoji": "🇲🇭"},
"MKD": {"title":"Macedonia","emoji": "🇲🇰"},
"MLI": {"title":"Mali","emoji": "🇲🇱"},
"MLT": {"title":"Malta","emoji": "🇲🇹"},
"MMR": {"title":"Myanmar","emoji": "🇲🇲"},
"MNE": {"title":"Montenegro","emoji": "🇲🇪"},
"MNG": {"title":"Mongolia","emoji": "🇲🇳"},
"MNP": {"title":"Northern Mariana Islands","emoji": "🇲🇵"},
"MOZ": {"title":"Mozambique","emoji": "🇲🇿"},
"MRT": {"title":"Mauritania","emoji": "🇲🇷"},
"MSR": {"title":"Montserrat","emoji": "🇲🇸"},
"MTQ": {"title":"Martinique","emoji": "🇲🇶"},
"MUS": {"title":"Mauritius","emoji": "🇲🇺"},
"MWI": {"title":"Malawi","emoji": "🇲🇼"},
"MYS": {"title":"Malaysia","emoji": "🇲🇾"},
"MYT": {"title":"Mayotte","emoji": "🇾🇹"},
"NAM": {"title":"Namibia","emoji": "🇳🇦"},
"NCL": {"title":"New Caledonia","emoji": "🇳🇨"},
"NER": {"title":"Niger","emoji": "🇳🇪"},
"NFK": {"title":"Norfolk Island","emoji": "🇳🇫"},
"NGA": {"title":"Nigeria","emoji": "🇳🇬"},
"NIC": {"title":"Nicaragua","emoji": "🇳🇮"},
"NIU": {"title":"Niue","emoji": "🇳🇺"},
"NLD": {"title":"Netherlands","emoji": "🇳🇱"},
"NOR": {"title":"Norway","emoji": "🇳🇴"},
"NPL": {"title":"Nepal","emoji": "🇳🇵"},
"NRU": {"title":"Nauru","emoji": "🇳🇷"},
"NZL": {"title":"New Zealand","emoji": "🇳🇿"},
"OMN": {"title":"Oman","emoji": "🇴🇲"},
"PAK": {"title":"Pakistan","emoji": "🇵🇰"},
"PAN": {"title":"Panama","emoji": "🇵🇦"},
"PCN": {"title":"Pitcairn","emoji": "🇵🇳"},
"PER": {"title":"Peru","emoji": "🇵🇪"},
"PHL": {"title":"Philippines","emoji": "🇵🇭"},
"PLW": {"title":"Palau","emoji": "🇵🇼"},
"PNG": {"title":"Papua New Guinea","emoji": "🇵🇬"},
"POL": {"title":"Poland","emoji": "🇵🇱"},
"PRI": {"title":"Puerto Rico","emoji": "🇵🇷"},
"PRK": {"title":"Korea, Democratic People's Republic of","emoji": "🇰🇵"},
"PRT": {"title":"Portugal","emoji": "🇵🇹"},
"PRY": {"title":"Paraguay","emoji": "🇵🇾"},
"PSE": {"title":"Palestinian Territory, Occupied","emoji": "🇵🇸"},
"PYF": {"title":"French Polynesia","emoji": "🇵🇫"},
"QAT": {"title":"Qatar","emoji": "🇶🇦"},
"REU": {"title":"Réunion","emoji": "🇷🇪"},
"ROU": {"title":"Romania","emoji": "🇷🇴"},
"RUS": {"title":"Russian Federation","emoji": "🇷🇺"},
"RWA": {"title":"Rwanda","emoji": "🇷🇼"},
"SAU": {"title":"Saudi Arabia","emoji": "🇸🇦"},
"SDN": {"title":"Sudan","emoji": "🇸🇩"},
"SSD": {"title":"South Sudan","emoji": "🇸🇸"},
"SEN": {"title":"Senegal","emoji": "🇸🇳"},
"SGP": {"title":"Singapore","emoji": "🇸🇬"},
"SGS": {"title":"South Georgia and the South Sandwich Islands","emoji": "🇬🇸"},
"SHN": {"title":"Saint Helena, Ascension and Tristan da Cunha","emoji": "🇸🇭"},
"SJM": {"title":"Svalbard and Jan Mayen","emoji": "🇸🇯"},
"SLB": {"title":"Solomon Islands","emoji": "🇸🇧"},
"SLE": {"title":"Sierra Leone","emoji": "🇸🇱"},
"SLV": {"title":"El Salvador","emoji": "🇸🇻"},
"SMR": {"title":"San Marino","emoji": "🇸🇲"},
"SOM": {"title":"Somalia","emoji": "🇸🇴"},
"SPM": {"title":"Saint Pierre and Miquelon","emoji": "🇵🇲"},
"SRB": {"title":"Serbia","emoji": "🇷🇸"},
"STP": {"title":"Sao Tome and Principe","emoji": "🇸🇹"},
"SUR": {"title":"Suriname","emoji": "🇸🇷"},
"SVK": {"title":"Slovakia","emoji": "🇸🇰"},
"SVN": {"title":"Slovenia","emoji": "🇸🇮"},
"SWE": {"title":"Sweden","emoji": "🇸🇪"},
"SWZ": {"title":"Swaziland","emoji": "🇸🇿"},
"SXM": {"title":"Sint Maarten (Dutch part)","emoji": "🇸🇽"},
"SYC": {"title":"Seychelles","emoji": "🇸🇨"},
"SYR": {"title":"Syrian Arab Republic","emoji": "🇸🇾"},
"TCA": {"title":"Turks and Caicos Islands","emoji": "🇹🇨"},
"TCD": {"title":"Chad","emoji": "🇹🇩"},
"TGO": {"title":"Togo","emoji": "🇹🇬"},
"THA": {"title":"Thailand","emoji": "🇹🇭"},
"TJK": {"title":"Tajikistan","emoji": "🇹🇯"},
"TKL": {"title":"Tokelau","emoji": "🇹🇰"},
"TKM": {"title":"Turkmenistan","emoji": "🇹🇲"},
"TLS": {"title":"Timor-Leste","emoji": "🇹🇱"},
"TON": {"title":"Tonga","emoji": "🇹🇴"},
"TTO": {"title":"Trinidad and Tobago","emoji": "🇹🇹"},
"TUN": {"title":"Tunisia","emoji": "🇹🇳"},
"TUR": {"title":"Turkey","emoji": "🇹🇷"},
"TUV": {"title":"Tuvalu","emoji": "🇹🇻"},
"TWN": {"title":"Taiwan, Province of China","emoji": "🇹🇼"},
"TZA": {"title":"Tanzania, United Republic of","emoji": "🇹🇿"},
"UGA": {"title":"Uganda","emoji": "🇺🇬"},
"UKR": {"title":"Ukraine","emoji": "🇺🇦"},
"UMI": {"title":"United States Minor Outlying Islands","emoji": "🇺🇲"},
"URY": {"title":"Uruguay","emoji": "🇺🇾"},
"USA": {"title":"United States","emoji": "🇺🇸"},
"UZB": {"title":"Uzbekistan","emoji": "🇺🇿"},
"VAT": {"title":"Holy See (Vatican City State)","emoji": "🇻🇦"},
"VCT": {"title":"Saint Vincent and the Grenadines","emoji": "🇻🇨"},
"VEN": {"title":"Venezuela, Bolivarian Republic of","emoji": "🇻🇪"},
"VGB": {"title":"Virgin Islands, British","emoji": "🇻🇬"},
"VIR": {"title":"Virgin Islands, U.S.","emoji": "🇻🇮"},
"VNM": {"title":"Viet Nam","emoji": "🇻🇳"},
"VUT": {"title":"Vanuatu","emoji": "🇻🇺"},
"WLF": {"title":"Wallis and Futuna","emoji": "🇼🇫"},
"WSM": {"title":"Samoa","emoji": "🇼🇸"},
"YEM": {"title":"Yemen","emoji": "🇾🇪"},
"ZAF": {"title":"South Africa","emoji": "🇿🇦"},
"ZMB": {"title":"Zambia","emoji": "🇿🇲"},
"ZWE": {"title":"Zimbabwe","emoji": "🇿🇼"},

}

dataset_licenses = {
    "CC0-1.0": {
        "url": "https://creativecommons.org/publicdomain/zero/1.0/",
        "title": "Creative Commons CCZero",
    },
    "CC-BY-4.0": {
        "url": "https://creativecommons.org/licenses/by/4.0/",
        "title": "Creative Commons Attribution 4.0",
    },
    "CC-BY-SA-4.0": {
        "url": "https://creativecommons.org/licenses/by-sa/4.0/",
        "title": "Creative Commons Attribution Share-Alike 4.0",
    },
    "CC-BY-NC-SA-4.0": {
        "url": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
        "title": "Creative Commons Attribution-NonCommercial-Share-Alike 4.0",
    },
    "CC-BY-ND 4.0": {
        "url": "https://creativecommons.org/licenses/by-nd/4.0/",
        "title": "Creative Commons Attribution-NoDerivatives 4.0 International",
    },
    "CC-BY-NC-ND 4.0": {
        "url": "https://creativecommons.org/licenses/by-nc-nd/4.0/",
        "title": "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International",
    },
    "CC-BY-IGO-3.0": {
        "url": "https://creativecommons.org/licenses/by-sa/3.0/igo/",
        "title": "Creative Commons Attribution for Intergovernmental Organisations",
    },
    "GPL": {
        "url": "https://www.gnu.org/licenses/gpl-3.0-standalone.html",
        "title": "GNU General Public License",
    },
    "MIT": {"url": "https://opensource.org/license/MIT", "title": "The MIT License"},
    "PDDL-1.0": {
        "url": "http://opendatacommons.org/licenses/pddl/1.0/",
        "title": "Open Data Commons Public Domain Dedication and License",
    },
    "ODbL-1.0": {
        "url": "https://opendatacommons.org/licenses/odbl/1-0",
        "title": "Open Data Commons Open Database License",
    },
}
